### ISSUE TITLE
Intermediatory screen on signed in auth state

### ISSUE THREAD

**Issue by dgiri-227** [atif2112011/Socialpi_admin#3]
If a user is signed in and they refresh the app, the login screen flashes for a couple of seconds on the app before the app changes to a signed in state. 
Please use appropriate intermediatory screens for such transitions. 
A useState hook can be used, it can be triggered in the useEffect where onAuthStateChanged is being implemented.

**Comment by atif2112011** [comment]
Fixed #0901ad1
