### ISSUE TITLE
Account Selection on Sign Up

### ISSUE THREAD

**Issue by dgiri-227** [atif2112011/Socialpi_admin#7]
The account selection popup needs to be presented to the user everytime when they sign in through google.
As of now it doesn't prompt the user to select an account to continue with google if the user has signed in previously and then signed out.

Steps to reproduce this bug 
1. sign in with a Gmail account X
2. sign out
3. sign in again, it will automatically sign you in with the previously used X account (this is buggy, user should get option to select an email account again)

**Comment by atif2112011** [comment]
Fixed #c3eb13a
